apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodbpv
  namespace: database
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  # persistentVolumeReclaimPolicy: Retain
  # storageClassName: mongodb-storage
  hostPath:
    path: /mnt/data
    # type: DirectoryOrCreate
