apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodbpvc
  namespace: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # volumeMode: Filesystem
